#######################################################################################
################### EFFECT OF taVNS ON HRV - A BAYESIAN META-ANALYSIS #################
#######################################################################################

################### Shiny App v.2 21.12.2020 UI #######################################

# Load required packages and source helper functions #----
library(shiny)
library(bayesmeta)
library(cowplot)
library(dplyr)
library(DT)
library(data.table)
library(esc)
library(ggplot2)
library(MAd)
library(readr)
library(R.rsp)
library(shinyBS)
library(shinycssloaders)
library(shinythemes)
library(stringr)
library(tidyr)
library(xtable)
source("HelperFunctions.R")
#----
# Define UI
ui <- fluidPage(theme = shinytheme("cosmo"),
                titlePanel(title = div("The influence of taVNS on HRV - a Bayesian living & interactive meta-analysis", 
                                       img(src='ukt.png',style="width: 200px", align = "right")),
                           windowTitle = "taVNS on HRV | Bayesian living & interactive MA"),
                sidebarLayout(
                  sidebarPanel(fluidRow(
                    tabsetPanel(
                      tabPanel("Study criteria",
                               br(), checkboxGroupInput(inputId = "design", label = p("Study design",style="color:#333333",
                                                                                 tags$style(type = "text/css", "#q1 {vertical-align: top;}"),
                                                                                 bsButton("q1", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")), 
                                                  choices = levels(df$Design), selected = levels(df$Design)),
                                        bsPopover(id="q1", title = "Study design.",
                                            content = paste0("<p>Choose to include effect sizes calculated within subjects, between subjects, or both.",
                                                             "<p>Default: both."),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               checkboxGroupInput(inputId = "control", label = p("Control type",style="color:#333333",
                                                                                 tags$style(type = "text/css", "#q2 {vertical-align: top;}"),
                                                                                 bsButton("q2", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),  
                                                  choices = levels(df$Control.Type), selected = c("earlobe sham", "no stimulation sham")),
                                       bsPopover(id="q2", title = "Control type.",
                                            content = paste0("<p>Choose to include effect sizes comparing against different types of sham stimulation, baseline HRV, or both.",
                                                             "<p>Default: earlobe sham and no stimulation sham."),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               checkboxGroupInput(inputId = "hrvparam", label = p("Heart rate variability parameter",style="color:#333333",
                                                                                  tags$style(type = "text/css", "#q3 {vertical-align: top;}"),
                                                                                  bsButton("q3", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")), 
                                                  choices = levels(df$HRV.Parameter), selected = c("RMSSD", "HF-HRV", "pNN50")),
                                         bsPopover(id="q3", title = "Heart rate variability parameter.",
                                            content = paste0("<p>Choose to include effect sizes with the following HRV parameters as dependent variables.",
                                                             "<p>RMSSD: Root mean square of successive differences.",
                                                             "<p>HF-HRV: High frequency power HRV.",
                                                             "<p>pNN50: Percentage of successive normal sinus RR intervals more than 50ms apart.",
                                                             "<p>LF/HF Ratio: Ratio of low to high frequencies.",
                                                             "<p>SDNN: Standard deviation of all R-to-R intervals.",
                                                             "<p>CVT: Cardiac vagal tone.",
                                                             "<p>Default: RMSSD, HF-HRV, pNN50"),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               checkboxGroupInput(inputId = "sample", label = p("Sample",style="color:#333333",
                                                                                tags$style(type = "text/css", "#q4 {vertical-align: top;}"),
                                                                                bsButton("q4", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),  
                                                  choices = levels(df$Sample), selected = "healthy"),
                                        bsPopover(id="q4", title = "Sample.",
                                            content = paste0("<p>Choose to include effect sizes with healthy participants and/or different patient samples.",
                                                             "<p>Default: healthy."),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               sliderInput(inputId = "gender", label = p("Percent females",style="color:#333333",
                                                                         tags$style(type = "text/css", "#q5 {vertical-align: top;}"),
                                                                         bsButton("q5", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),  
                                           min = min(df$Percent.Females), max = max(df$Percent.Females), value = c(min(df$Percent.Females), max(df$Percent.Females)), step = 1, sep = "", ticks = F),
                                        bsPopover(id="q5", title = "Percent females.",
                                            content = paste0("<p>Choose to include effect sizes with a certain percentage of female participants.",
                                                          "<p>Default: all."),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               sliderInput(inputId = "age", label = p("Age",style="color:#333333",
                                                              tags$style(type = "text/css", "#q6 {vertical-align: top;}"),
                                                              bsButton("q6", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),   
                                           min = min(df$Mean.Age), max = max(df$Mean.Age), value = c(min(df$Mean.Age), max(df$Mean.Age)), step = 1, sep = "", ticks = F),
                                        bsPopover(id="q6", title = "Age.",
                                            content = paste0("<p>Choose to include effect sizes with a certain mean age of participants.",
                                                             "<p>Default: all."),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               checkboxGroupInput(inputId = "blind", label = p("Blinding",style="color:#333333",
                                                                               tags$style(type = "text/css", "#q7 {vertical-align: top;}"),
                                                                               bsButton("q7", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),    
                                                  choices = levels(df$Blindness), selected = c("single blind", "double blind")),
                                        bsPopover(id="q7", title = "Blinding.",
                                            content = paste0("<p>Choose to include effect sizes from studies with certain degrees of blindness.",
                                                             "<p>Default: Double blind and single blind."),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               sliderInput(inputId = "pubyear", label = p("Publication year",style="color:#333333",
                                                                          tags$style(type = "text/css", "#q8 {vertical-align: top;}"),
                                                                          bsButton("q8", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")), 
                                           min = min(df$Publication.Year), max = max(df$Publication.Year), value = c(min(df$Publication.Year), max(df$Publication.Year)), step = 1, sep = "", ticks = F),
                                        bsPopover(id="q8", title = "Publication year.",
                                            content = paste0("<p>Choose to include effect sizes from studies with a certain range of publication years.",
                                                             "<p>Default: all."),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               checkboxGroupInput(inputId = "included", label = p("Include/exclude specific studies",style="color:#333333",
                                                                          tags$style(type = "text/css", "#q9 {vertical-align: top;}"),
                                                                          bsButton("q9", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")), 
                                                  choices = levels(df$study), selected = levels(df$study)),
                                bsPopover(id="q9", title = "Include/exclude specific studies.",
                                    content = paste0("<p>Exclude specific studies by removing the tick mark.",
                                                     "<p>This selection is hierarchically below the other inclusion/exclusion criteria.",
                                                     "<p>If for example Trobec (2020) is excluded, because atrial fibrillation patients are not selected for inclusion above, this study will not be included in the analysis, even though it is still ticked here.",
                                                     "<p>However, if atrial fibrillation patients are selected for inclusion above, but Trobec (2020) is unticked here, the study will not be included."),
                                   placement = "right", 
                                   trigger = "click",
                                   options = list(container = "body"))),
                      tabPanel("taVNS specifications",
                               br(), checkboxGroupInput(inputId = "side", label = p("Stimulation side",style="color:#333333",
                                                                              tags$style(type = "text/css", "#q10 {vertical-align: top;}"),
                                                                              bsButton("q10", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")), 
                                                  choices = levels(df$Stimulation.side), selected = levels(df$Stimulation.side)),
                                        bsPopover(id="q10", title = "Stimulation side.",
                                            content = paste0("<p>Choose to include effect sizes from studies that placed the stimulation electrode on the left ear, right ear and/or bilaterally.",
                                                             "<p>Default: all."),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               checkboxGroupInput(inputId = "part", label = p("Stimulation site",style="color:#333333",
                                                                              tags$style(type = "text/css", "#q11 {vertical-align: top;}"),
                                                                              bsButton("q11", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),  
                                                  choices = levels(df$Part.of.the.ear.stimulated), selected = levels(df$Part.of.the.ear.stimulated)),
                                        bsPopover(id="q11", title = "Stimulation site.",
                                            content = paste0("<p>Choose to include effect sizes from studies that placed the stimulation electrode on the tragus, cymba conchae and/or cavum conchae.",
                                                             "<p>Default: all."),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               sliderInput(inputId = "stimduration", label = p("Stimulation duration (in sec.)",style="color:#333333",
                                                                               tags$style(type = "text/css", "#q12 {vertical-align: top;}"),
                                                                               bsButton("q12", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),  
                                           min = min(df$Stimulation.duration.sec.), max = max(df$Stimulation.duration.sec.), value = c(min(df$Stimulation.duration.sec.), max(df$Stimulation.duration.sec.)), step = 10, sep = "", ticks = F),
                                        bsPopover(id="q12", title = "Stimulation duration (in sec.).",
                                            content = paste0("<p>Choose to include effect sizes from studies that applied taVNS for a certain amount of time.",
                                                             "<p>Default: all."),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               checkboxGroupInput(inputId = "intensity1", label = p("Intensity chosen",style="color:#333333",
                                                                                    tags$style(type = "text/css", "#q13 {vertical-align: top;}"),
                                                                                    bsButton("q13", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),   
                                                  choices = levels(df$Intensity.fixed.or.mean), selected = levels(df$Intensity.fixed.or.mean)),
                                        bsPopover(id="q13", title = "Intensity chosen.",
                                            content = paste0("<p>Choose to include effect sizes from studies that determined taVNS intensity for each subject individually or used a fixed value across all participants.",
                                                             "<p>Default: both."),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               checkboxGroupInput(inputId = "device", label = p("taVNS device",style="color:#333333",
                                                                                tags$style(type = "text/css", "#q14 {vertical-align: top;}"),
                                                                                bsButton("q14", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),    
                                                  choices = levels(df$taVNS.Device), selected = levels(df$taVNS.Device)),
                                        bsPopover(id="q14", title = "taVNS device.",
                                            content = paste0("<p>Choose to include effect sizes from studies that used taVNS devices manufactured by cerbomed, a TENS device or an other, unspecified device.",
                                                             "<p>Default: all."),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               sliderInput(inputId = "intensity2", label = p("Intensity (in mA)",style="color:#333333",
                                                                             tags$style(type = "text/css", "#q15 {vertical-align: top;}"),
                                                                             bsButton("q15", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),  
                                           min = min(df$Mean.Intensity..mA.), max = max(df$Mean.Intensity..mA.), value = c(min(df$Mean.Intensity..mA.), max(df$Mean.Intensity..mA.)), step = 0.1, sep = "", ticks = F)),
                                        bsPopover(id="q15", title = "Intensity (in mA).",
                                            content = paste0("<p>Choose to include effect sizes from studies that applied taVNS with a certain mean intensity (in mA).",
                                                             "<p>Default: all."),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                      tabPanel("Prior specifications",
                               br(), numericInput(inputId = "mupriormean", label = p("µ prior mean",style="color:#333333",
                                                                               tags$style(type = "text/css", "#q16 {vertical-align: top;}"),
                                                                               bsButton("q16", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),   
                                            value = 0, step = 0.1),
                                        bsPopover(id="q16", title = "µ prior mean.",
                                            content = paste0("<p>Set the mean of your µ prior (effect).",
                                                             "<p>Note that the results and their interpretability are drastically influenced by prior choices.",
                                                             "<p>Default: 0"),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               numericInput(inputId = "mupriorsd", label = p("µ prior standard deviation", style="color:#333333",
                                                                             tags$style(type = "text/css", "#q17 {vertical-align: top;}"),
                                                                             bsButton("q17", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),    
                                            value = 1.5, step = 0.1, min = 0),
                                        bsPopover(id="q17", title = "µ prior standard deviation.",
                                            content = paste0("<p>Set the standard deviation of your µ prior (effect).",
                                                             "<p>Note that the results and their interpretability are drastically influenced by prior choices.",
                                                             "<p>Default: 1.5"),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               radioButtons(inputId = "robust", label = p("µ Bayes Factor robustness check", style="color:#333333",
                                                                          tags$style(type = "text/css", "#q18 {vertical-align: top;}"),
                                                                          bsButton("q18", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),    
                                            choices = c(No = "No", Yes = "Yes")),
                                        bsPopover(id="q18", title = "µ Bayes Factor robustness check.",
                                            content = paste0("<p>Bayes Factors over a variety of prior standard deviations will be plotted.",
                                                             "<p>Note that selecting Yes will lead to an increase in computation time and that the plot will only be computed if priors for τ and μ are proper.",
                                                             "<p>Default: No."),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               radioButtons(inputId = "tauprior", label = p("τ prior", style="color:#333333",
                                                                            tags$style(type = "text/css", "#q19 {vertical-align: top;}"),
                                                                            bsButton("q19", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),    
                                            choices = c("Half cauchy", "Half student t","uniform", "sqrt", "Jeffreys", "BergerDeely", "conventional", "DuMouchel", "shrinkage", "I2")),
                                        bsPopover(id="q19", title = "τ prior.",
                                            content = paste0("<p>Choose your τ prior.",
                                                             "<p>Note that the results and their interpretability are drastically influenced by prior choices.",
                                                             "<p>Default: Half cauchy."),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               numericInput(inputId="scaletau", label = p("τ prior scale (for half cauchy or half student t)",style="color:#333333",
                                                                          tags$style(type = "text/css", "#q20 {vertical-align: top;}"),
                                                                          bsButton("q20", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),    
                                            value=0.5, step=0.05),
                               bsPopover(id="q20", title = "τ prior scale.",
                                         content = paste0("<p>Set the scale of your τ prior (if a half cauchy or a half student t prior is selected).",
                                                          "<p>Note that the results and their interpretability are drastically influenced by prior choices.",
                                                          "<p>Default: 0.5"),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               a("Further information on choosing an appropriate τ prior.", href="https://cran.r-project.org/web/packages/bayesmeta/bayesmeta.pdf", target = "_blank")),
                      hr(),
                      submitButton("Re-Calculate Meta-Analysis", icon("sync"))
                    ))),
                  mainPanel(
                    fluidRow(
                      tabsetPanel(
                        tabPanel("Explanation", br(),
                                 h3("Welcome to the living & interactive meta-analysis on the influence of transcutaneous auricular vagus nerve stimulation (taVNS) on heart rate variablilty (HRV)."), br(),
                                 h4("Purpose:"),
                                 p("Non-invasive brain stimulation techniques, such as transcutaneous auricular vagus nerve stimulation (taVNS), have considerable potential for clinical use. Beneficial effects of taVNS have been demonstrated on symptoms in patients with mental or neurological disorders as well as transdiagnostic dimensions, including mood and motivation. However, since taVNS research is still an emerging field, the underlying neurophysiological processes are not yet fully understood, and the replicability of findings on biomarkers of taVNS effects has been questioned. Here, we perform a living Bayesian random effects meta-analysis to synthesize the current evidence concerning the effects of taVNS on heart rate variability (HRV), a candidate biomarker that has, so far, received most attention in the field. To keep the synthesis of evidence transparent and up to date as new studies are being published, we developed a Shiny web app that regularly incorporates new results and enables users to modify study selection criteria to evaluate the robustness of the inference across potential confounds. By increasing transparency and timeliness, we believe that the concept of living meta-analyses can lead to transformational benefits in emerging fields such as non-invasive brain stimulation."), br(),
                                 h4("Explanation:"),
                                 p("Select inclusion criteria and prior settings in the panel on the left. Click 'Re-Calculate Meta-Analysis' to rerun the analysis. Results are displayed in the central panels."), br(),
                                 h4("Paper:"),
                                 ("This app accompanies the following "),
                                 a("paper", href="https://doi.org/10.1101/2021.01.18.426704", target = "_blank"), 
                                 ("where a more detailed explanation and an exemplary analysis can be found. Inclusion criteria and prior settings of the exemplary analysis correspond to thus app's default criteria."), br(), br(),
                                 h4("Code and data:"),
                                 ("This app's R Code and datasets can be found "),
                                 a("here", href="https://github.com/neuromadlab/taVNSHRVmeta", target = "_blank"),
                                 ("on GitHub."), br(), br(),
                                 h4("Adding new results:"),
                                 p("A living meta-analysis means a growing meta-analysis. Therefore, if we either missed a paper, you published results which are not yet shown in the 'Full texts screened'-table or you have unpublished HRV data of your taVNS experiments, please contact us."), br(), br(),
                                 h4("Contact:"),
                                 p("The app is maintained by neuroMADLAB (Neuroscience of Motivation, Action, & Desire) at the University of Tuebingen, Germany."),
                                 p("Contact/Visit us:"),
                                   a(shiny::actionButton(inputId = "email1", 
                                                         label = "Mail", 
                                                         icon = icon("envelope", lib = "font-awesome")),
                                     href="mailto:neuromadlab@klinikum.uni-tuebingen.de"),
                                   a(shiny::actionButton(inputId = "website", 
                                                         label = "Web", 
                                                         icon = icon("globe", lib = "font-awesome")),
                                     href="http://www.neuromadlab.com"),
                                   a(shiny::actionButton(inputId = "website", 
                                                         label = "Twitter", 
                                                         icon = icon("twitter", lib = "font-awesome")),
                                     href="http://www.twitter.com/neuromadlab")
                                 ),
                        tabPanel("Study overview", br(),
                                 h4("This table provides an overview of the studies included in the analysis:"),
                                 textOutput("warning"), br(),
                                 DT::dataTableOutput("studies") %>% withSpinner(type = 6, color = "#3498DB"), br(),
                                 h4("Abbreviations:"), p("RMSSD: root mean square of successive differences; 
                                   HF-HRV: high frequency heart rate variability; 
                                   pNN50: percentage of successive normal sinus RR intervals more than 50ms;
                                   LF/HF Ratio: low frequency to high frequency ratio;
                                   SDNN: standard deviation of all R-to-R intervals;
                                   CVT: cardiac vagal tone calculated with 'phase shift demodulation'.")),
                        tabPanel("Outlier check", br(),
                                 h4("Boxplot graph:"), plotOutput("boxplot") %>% withSpinner(type = 6, color = "#3498DB")),
                        tabPanel("Forest plot", br(),
                                 h4("Forest plot with 95% credible intervals:"),
                                 plotOutput("forest") %>% withSpinner(type = 6, color = "#3498DB")),
                        tabPanel("Funnel plot", br(),
                                 h4("Funnel plot to assess publication bias:"),
                                 plotOutput("funnel")  %>% withSpinner(type = 6, color = "#3498DB")),
                        tabPanel("Statistics", br(),
                                 h4("Parameters:"),
                                 p("τ (tau): posterior distribution of heterogeneity."),
                                 p("μ (mu): posterior distribution of effect."),
                                 p("θ (theta): 'predictive distribution, that expresses the posterior knowledge about a future observation, i.e., an additional draw θk+1 from the underlying population of studies.' (Röver, 2020, p. 16)."),
                                 ("Statistics are calculated/estimated using the bayesmeta package "), 
                                 a("(Röver, 2020).", href="http://dx.doi.org/10.18637/jss.v093.i06", target = "_blank"),
                                 ("The corresponding github page can be found "),
                                 a("here.", href = "https://github.com/cran/bayesmeta", target = "_blank"), br(),
                                 h4("Bayes factors:"), verbatimTextOutput("bf") %>% withSpinner(type = 6, color = "#3498DB"),
                                 p("Bayes factors are only computed if the priors for τ and μ are proper."), br(),
                                 h4("Marginal posterior summary:"), verbatimTextOutput("summary") %>% withSpinner(type = 6, color = "#3498DB"), br(),
                                 h4("Maximum-likelihood:"), verbatimTextOutput("ML") %>% withSpinner(type = 6, color = "#3498DB"), br(),
                                 h4("Joint maximum-a-posteriori:"), verbatimTextOutput("MAP") %>% withSpinner(type = 6, color = "#3498DB")),
                        tabPanel("Full texts screened", br(),
                                 h4("This table provides an overview of all full-text we assessed for eligibility:"),
                                 DT::dataTableOutput("screened") %>% withSpinner(type = 6, color = "#3498DB"), br(),
                                 h4("Adding new results:"),
                                 ("A living meta-analysis means a growing meta-analysis. Therefore, if we either missed a paper, you published results which are not yet shown in this table or you have unpublished HRV data of your taVNS experiments, please"),
                                 a("contact us.", href="mailto:neuromadlab@klinikum.uni-tuebingen.de", target = "_blank")),
                        tabPanel("Additional plots", br(),
                                 h4("Joint posterior density of heterogeneity τ and effect μ:"), plotOutput("joint") %>%  withSpinner(type = 6, color = "#3498DB"),
                                 p("Darker shading corresponds to higher probability density."),
                                 p("Red lines indicate (approximate) 2-dimensional credible regions,"),
                                 p("green lines show marginal posterior medians and 95% credible intervals,"),
                                 p("blue lines show conditional posterior mean effect as a function of the heterogeneity along with a 95% interval."),
                                 p("Red cross (+): posterior mode"),
                                 p("Pink cross (x): ML estimate"), br(),
                                 h4("Prior, posterior, & likelihood:"), plotOutput("evupdate") %>% withSpinner(type = 6, color = "#3498DB"), br(),
                                 h4("τ prior distribution:"), plotOutput("taupriorplot") %>% withSpinner(type = 6, color = "#3498DB")),
                        tabPanel("Bayes factor robustness check", br(),
                                 h4("Bayes Factors over a variety of prior standard deviations:"),
                                 p("Will only be computed if 'Yes' is selected for 'µ Bayes Factor robustness check' and the priors for τ and μ are proper."),br(),
                                 conditionalPanel(condition = "input.tauprior == 'uniform' | 
                                                               input.tauprior == 'sqrt' |
                                                               input.tauprior == 'Jeffreys' |
                                                               input.tauprior == 'BergerDeely' | 
                                                               input.tauprior == 'conventional' | 
                                                               input.tauprior == 'DuMouchel' | 
                                                               input.tauprior == 'shrinkage' | 
                                                               input.tauprior == 'I2'",
                                                  textOutput("warning2")),
                                 conditionalPanel(condition = "input.robust == 'Yes'", 
                                                  plotOutput("robustplot") %>% withSpinner(type = 6, color = "#3498DB"),
                                 p("Default: 1.5 (orange horizontal line)"),
                                 p("Narrow: user selected standard deviation / 2"),
                                 p("User: user selected standard deviation"),
                                 p("Wide: user selected standard deviation + 1"),
                                 p("Ultrawide: user selected standard deviation + 2"),
                                 p("Interpretations of Bayes factors are based on Jeffreys (1961) with slight modifications by Lee and Wagenmakers (2013) and should be considered with caution.")))
                          )
                        )
                      )
                    )
                  )
                
